wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.7.5
    start_time: 1651938643
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      2:
      - 1
      - 9
      - 41
      - 55
      3:
      - 2
      4: 3.7.5
      5: 0.12.15
      8:
      - 2
      - 5
accelerator:
  desc: null
  value: null
accumulate_grad_batches:
  desc: null
  value: null
amp_backend:
  desc: null
  value: native
amp_level:
  desc: null
  value: null
auto_lr_find:
  desc: null
  value: false
auto_scale_batch_size:
  desc: null
  value: false
auto_select_gpus:
  desc: null
  value: false
avg_reward_len:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 64
benchmark:
  desc: null
  value: null
check_val_every_n_epoch:
  desc: null
  value: 1
checkpoint_callback:
  desc: null
  value: null
critic_beta:
  desc: null
  value: 0.5
default_root_dir:
  desc: null
  value: null
detect_anomaly:
  desc: null
  value: false
deterministic:
  desc: null
  value: false
devices:
  desc: null
  value: null
enable_checkpointing:
  desc: null
  value: true
enable_model_summary:
  desc: null
  value: true
enable_progress_bar:
  desc: null
  value: true
entropy_beta:
  desc: null
  value: 0.01
env:
  desc: null
  value: WordleEnv100-v0
epoch_len:
  desc: null
  value: 10
fast_dev_run:
  desc: null
  value: false
flush_logs_every_n_steps:
  desc: null
  value: null
gamma:
  desc: null
  value: 0.99
gpus:
  desc: null
  value: null
gradient_clip_algorithm:
  desc: null
  value: null
gradient_clip_val:
  desc: null
  value: null
hidden_size:
  desc: null
  value: 256
ipus:
  desc: null
  value: null
limit_predict_batches:
  desc: null
  value: null
limit_test_batches:
  desc: null
  value: null
limit_train_batches:
  desc: null
  value: null
limit_val_batches:
  desc: null
  value: null
log_every_n_steps:
  desc: null
  value: 50
log_gpu_memory:
  desc: null
  value: null
logger:
  desc: null
  value: true
lr:
  desc: null
  value: 0.0001
max_epochs:
  desc: null
  value: null
max_steps:
  desc: null
  value: -1
max_time:
  desc: null
  value: null
min_epochs:
  desc: null
  value: null
min_steps:
  desc: null
  value: null
move_metrics_to_cpu:
  desc: null
  value: false
multiple_trainloader_mode:
  desc: null
  value: max_size_cycle
n_hidden:
  desc: null
  value: 1
network_name:
  desc: null
  value: SumChars
num_nodes:
  desc: null
  value: 1
num_processes:
  desc: null
  value: null
num_sanity_val_steps:
  desc: null
  value: 2
overfit_batches:
  desc: null
  value: 0.0
plugins:
  desc: null
  value: null
precision:
  desc: null
  value: 32
prepare_data_per_node:
  desc: null
  value: null
prob_cheat:
  desc: null
  value: 0
prob_play_lost_word:
  desc: null
  value: 0
process_position:
  desc: null
  value: 0
profiler:
  desc: null
  value: null
progress_bar_refresh_rate:
  desc: null
  value: null
reload_dataloaders_every_n_epochs:
  desc: null
  value: 0
replace_sampler_ddp:
  desc: null
  value: true
replay_size:
  desc: null
  value: 1000
resume_from_checkpoint:
  desc: null
  value: null
seed:
  desc: null
  value: 123
stochastic_weight_avg:
  desc: null
  value: false
strategy:
  desc: null
  value: null
sync_batchnorm:
  desc: null
  value: false
terminate_on_nan:
  desc: null
  value: null
tpu_cores:
  desc: null
  value: null
track_grad_norm:
  desc: null
  value: -1
val_check_interval:
  desc: null
  value: null
weight_decay:
  desc: null
  value: 0.0
weights_save_path:
  desc: null
  value: null
weights_summary:
  desc: null
  value: top
