wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.5
    start_time: 1651804035
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      4: 3.7.5
      5: 0.12.15
      8:
      - 5
