---
dataset:
    replay_size: 0
    init_winning_replays: ""
    replay_size: 1
    sample_size: 10000
training:
    batch_size: 1
    lr: 0.0001
    weight_decay: 0
    eps_end: 0
    eps_state: 0
    eps_last_frame: 1
    gamma: 0
    warmup: 0
agent:
    type: "SumChars"
    hidden_size: 5 
experiment:
    num_episodes: 1
    sync_rate: 0
    steps_per_update: 0
    use_gpu: False
